[vowels]
"अ" = "a"
"आ" = "-a"
"इ" = "i"
"ई" = "-i"
"उ" = "u"
"ऊ" = "-u"
"ऋ" = "r."
"ॠ" = "-r."
"ऌ" = "l."
"ॡ" = "-l."
"ऎ" = ""
"ए" = "e"
"ऐ" = "ai"
"ऒ" = ""
"ओ" = "o"
"औ" = "au"

[yogavaahas]
"ं" = "m."
"ः" = "h."
"ँ" = "~c"

[virama]
"्" = ""

[accents]
"॑" = "\!"
"॒" = "\_"
"᳚" = "\!\!"

[consonants]
"क" = "k"
"ख" = "kh"
"ग" = "g"
"घ" = "gh"
"ङ" = ".n"
"च" = "c"
"छ" = "ch"
"ज" = "j"
"झ" = "jh"
"ञ" = "~n"
"ट" = "t."
"ठ" = "t.h"
"ड" = "d."
"ढ" = "d.h"
"ण" = "n."
"त" = "t"
"थ" = "th"
"द" = "d"
"ध" = "dh"
"न" = "n"
"प" = "p"
"फ" = "ph"
"ब" = "b"
"भ" = "bh"
"म" = "m"
"य" = "y"
"र" = "r"
"ल" = "l"
"व" = "v"
"श" = "'s"
"ष" = "s."
"स" = "s"
"ह" = "h"
"ळ" = "~l"
"क्ष" = "ks."
"ज्ञ" = "j~n"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "OM"
"ऽ" = "'"
"।" = "|"
"॥" = "||"

[alternates]
"a": ["A"]
"-a": ["-A"]
"i": ["I"]
"-i": ["-I"]
"u": ["U"]
"-u": ["-U"]
"r.": ["R."]
"-r.": ["-R."]
"l.": ["L."]
"-l.": ["-L."]
"e": ["E"]
"ai": ["Ai"]
"o": ["O"]
"au": ["Au"]
"m.": ["M."]
"h.": ["H."]
"k": ["K"]
"kh": ["Kh"] 
"g": ["G"]
"gh": ["Gh"] 
".n": [".N"] 
"c": ["C"] 
"ch": ["Ch"] 
"j": ["J"]
"jh": ["Jh"] 
"~n": ["~N"] 
"t.": ["T."] 
"t.h": ["T.h"] 
"d.": ["D."]
"d.h": ["D.h"] 
"n.": ["N."]
"t": ["T"]
"th": ["Th"] 
"d": ["D"]
"dh": ["Dh"] 
"n": ["N"]
"p": ["P"] 
"ph": ["Ph"] 
"b": ["B"]
"bh": ["Bh"] 
"m": ["M"]
"y": ["Y"] 
"r": ["R"] 
"l": ["L"] 
"v": ["V"] 
"'s": ["'S"] 
"s.": ["S."] 
"s": ["S"]
"h": ["H"] 
"ks.": ["Ks."] 
"j~n": ["J~n"]
"|": ["."]
"||": [".."]